chapel/prayers/urls.py
from django.urls import path
from chapel.prayers.views import new, success, listing

app_name = 'prayers'

urlpatterns = [
    path('acender-vela/', new, name='new'),
    path('sucesso/', success, name='success'),
    path('velas-acesas/', listing, name='list')
]

chapel/urls.py
from django.contrib import admin
from django.urls import path, include
import chapel.core.views

urlpatterns = [
    path('', chapel.core.views.home),
    path('preces/', include('chapel.prayers.urls')),
    path('admin/', admin.site.urls),
]

chapel/core/models.py
from django.db import models

chapel/prayers/models.py
from django.db import models
from chapel.prayers.managers import LitManager


class Prayer(models.Model):
    name = models.CharField('nome', max_length=100)
    email = models.EmailField('email')
    description = models.TextField('intenção', max_length=220)
    created_at = models.DateTimeField('acesa em', auto_now_add=True)

    objects = LitManager()

    class Meta():
        verbose_name = 'intenção'
        verbose_name_plural = 'intenções'

    def __str__(self):
        return self.name

chapel/core/forms.py
from django import forms


class PrayersForm(forms.Form):
    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='Email')
    prayer = forms.CharField(label='Deixe sua prece',
                             widget=forms.Textarea(attrs={'rows': '5'}))

chapel/prayers/forms.py
from django.forms.widgets import Textarea
from chapel.prayers.models import Prayer
from django import forms


class PrayerForm(forms.ModelForm):
    class Meta:
        model = Prayer
        fields = ['name', 'email', 'description']
        widgets = {
            'description': Textarea(attrs={'rows': 5})
        }
        labels = {
            'description': 'Deixe sua prece'
        }

    def clean_name(self):
        name = self.cleaned_data['name']
        words = [w.capitalize() for w in name.split()]
        return ' '.join(words)

chapel/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')

chapel/prayers/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, resolve_url as r
from chapel.prayers.forms import PrayerForm
from chapel.prayers.models import Prayer


def new(request):
    if request.method == 'POST':
        return create(request)

    return empty_form(request)


def empty_form(request):
    return render(request, 'prayers/prayer_form.html', {'form': PrayerForm()})


def create(request):
    form = PrayerForm(request.POST)
    if not form.is_valid():
        return render(request, 'prayers/prayer_form.html', {'form': form})

    form.save()
    return HttpResponseRedirect(r('prayers:success'))


def success(request):
    return render(request, 'prayers/success.html')


def listing(request):
    context = {'prayers': Prayer.objects.lit_candles().order_by('-created_at')}
    return render(request, 'prayers/list.html', context)

chapel/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Capela Virtual{% endblock title %}</title>
  
  <link rel="stylesheet" href="{% static 'css/main.css' %}"></link>
  <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:wght@400;700;800&family=Montserrat:wght@300;500;600;700&display=swap" rel="stylesheet"></link>
  <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}"></link>
</head>
<body class="background">
  <main id="virtual-candle">
    {% include 'nav.html' %}

    {% block content %}
    {% endblock content%} 
  </main>
  
  <footer>
      &copy; 2020 | UNISAGRADO. Todos os direitos reservados.
  </footer>

  <script src="{% static 'js/swiper.min.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
  <script src="{% static 'js/vue-awesome-swiper.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

chapel/core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="welcome">
  <div class="container">
    <img src="{% static 'img/banner.svg' %}" />
    <div class="welcome-message">
      <p>Olá!</p>
      <p>
        Seja bem-vindo(a) a este local, onde você poderá deixar seus pedidos, 
        em intercessão a Bem-Aventurada Clélia Merloni.
      </p>
      <p>“Abraço-te no Sagrado Coração de Jesus e nEle te fecho, com a chave da oração.”</p>
      <em>Bem-Aventurada Clélia Merloni</em>
    </div>

    <div class="actions">
      <a class="round-button" role="button" title="Faça sua prece" href="{% url 'prayers:new' %}" @click="blowOutCandle">
        Acenda uma vela
      </a>
      <a class="round-button" role="button" title="Veja as velas acesas" href="{% url 'prayers:list' %}">
        Veja as velas acesas
      </a>
    </div>
  </div>

  <div class="show-lg" id="christ-pic">
    <img src="{% static 'img/christ.png' %}" alt="Imagem de cristo de braços abertos" />
  </div>
</section>
{% endblock content %}

chapel/core/templates/nav.html
{% load static %}
<header>
    <a href="/"><img src="{% static 'img/logo.png'%}" alt="Logo Unisagrado" /></a>
</header>
<nav class="nav-menu" role="navigation">
    <ul>
        <li><a class="nav-button" href="/">Início</a></li>
        <li><a class="nav-button" href="https://unisagrado.edu.br/no-unisagrado/pastoral">Sobre a pastoral</a></li>
    </ul>
</nav>

chapel/prayers/templates/prayers/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Velas acesas{% endblock title %}

{% block content %}
<section class="candle-container">
    <div class="prayers-container">
        <h1>Todas as preces!</h1>       
        <div class="carousel">
            <swiper 
                ref="swiperComponent"
                :options="swiperOptions"            
            >
                {% for prayer in prayers %}
                    <swiper-slide>
                        <div class="prayer">
                            <p>
                                {{ prayer.description }}  
                                <strong>- {{prayer.name}}</strong>
                            </p>
                            <img src="{% static 'img/candle_on.png' %}" alt="Vela acesa" />
                        </div>
                    </swiper-slide>
                {% empty %}
                    <div class="swiper-slide-empty">
                        <p>Não há nenhuma vela acesa</p>
                        <a class="round-button" role="button" title="Faça sua prece" href="{% url 'prayers:new' %}" @click="blowOutCandle">
                            Acenda uma vela
                        </a>
                    </div>
                {% endfor %}
                
                <div class="swiper-scrollbar" slot="scrollbar"></div>
                <div class="swiper-button swiper-button-prev" slot="button-prev"></div>
                <div class="swiper-button swiper-button-next" slot="button-next"></div>
            </swiper>        
        </div> 
    </div>
</section>
{% endblock content %}

chapel/prayers/templates/prayers/prayer_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Faça sua prece{% endblock title %}

{% block content %}
<section class="candle-container">
    <div class="show-lg" id="clelia_merloni-pic">
        <img src="{% static 'img/clelia_merloni.png' %}" alt="Bem-aventurada Clélia Merloni" />
    </div>
    <form action="." novalidate method="post">
        {% csrf_token %}
        <div class="form-row input-text label-block">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name.errors }}
            {{ form.name }}
        </div>
        <div class="form-row input-text label-block">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
            {{ form.email.errors }}
            {{ form.email }}
        </div>
        <div class="form-row input-text label-block">
            <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
            {{ form.description.errors }}
            {{ form.description }}
        </div>  

        <button class="round-button" role="button" type="submit">
            Enviar prece
        </button>
    </form>
</section>
{% endblock content %}

chapel/prayers/templates/prayers/success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Intenção enviada{% endblock title %}

{% block content %}
<section class="candle-container">
    <div class="success-container">
        <div class="show-lg" id="clelia_merloni-pic">
            <img src="{% static 'img/clelia_merloni.png' %}" alt="Bem-aventurada Clélia Merloni" />
        </div>
        <div class="success-message"> 
            <div class="balloon">
            <p>A Bem-Aventurada Clélia Merloni interceda por você e por suas intenções.</p>
            <div :class="litCandle? 'show': 'hide'" class="lit-candle-message">
                <p>sua vela ficará acesa por 7 dias</p>
            </div>
            </div>
            <img src="{% static 'img/msg_clelia_merloni.png' %}" alt="Abençoo-vos com cem corações. Bem-aventurada Clélia Merloni" />
            <a class="round-button" role="button" title="Veja as velas acesas" href="{% url 'prayers:list' %}">
                Veja as velas acesas
            </a>
        </div>
        <div class="candle" id="candle">
            <button class="candle-light" type="button" @click="lightCandle">
                <p :class="!litCandle? 'show': 'hide'">
                    Clique aqui para acender sua vela
                </p>
                <img :class="litCandle? 'show': 'hide'" id="id_candle-light" src="{% static 'img/candle-light.png'%}" alt="Chama" />
            </button>
            <img src="{% static 'img/candle.png' %}" />
        </div>
        
    </div>
</section>
{% endblock content %}